# plot2.png
datos <- read.csv("household_power_consumption.txt",as.is= TRUE, na.strings = "?", sep = ";", dec = ".",header = TRUE)
datos2 <- subset.data.frame(datos, Date == "1/2/2007" | Date == "2/2/2007",c(1:9))
fecha <- as.Date(datos2$Date, "%d/%m/%Y")
dia_sem <- weekdays(fecha,TRUE)
png(file="plot2.png", width = 480, height = 480)
plot(datos2$Global_active_power,type="l",ylab="Global Active Power (kilowatts)",axes=FALSE,frame.plot=TRUE,xlab='')
axis(2)
longitud <- length(datos2$Global_active_power)
axis(1,labels=c("Thu","Fri","Sat"), at=c(0,longitud/2,longitud))
dev.off()
