#plot3.png
library(graphics)
datos <- read.csv("household_power_consumption.txt",as.is= TRUE, na.strings = "?", sep = ";", dec = ".",header = TRUE)
datos2 <- subset.data.frame(datos, Date == "1/2/2007" | Date == "2/2/2007",c(1:9))
fecha <- as.Date(datos2$Date, "%d/%m/%Y")
dia_sem <- weekdays(fecha,TRUE)
longitud2 <- length(datos2$Sub_metering_1)
png(file="plot3.png", width = 480, height = 480)
plot(datos2$Sub_metering_1,col='black',type='l',axes=FALSE,frame.plot=TRUE,ylab='Energy sub metering',xlab='')
points(datos2$Sub_metering_2,col='red',type='l')
points(datos2$Sub_metering_3,col='blue',type='l')
axis(2)
axis(1,labels = c("Thu","Fri","Sat"), at = c(0,longitud2/2,longitud2))
legend('topright',c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),col = c('black','red','blue'), plot = TRUE, lwd=1)
dev.off()
